### ISSUE TITLE
Issue about ConnectInstaller

### ISSUE THREAD

**Issue by dawei-medaitek** [IBM/aspera-connect-sdk-js#17]
Dear Sir, hope you well , I have some questions,
when I check ConnectInstaller status through below code,  asperaInstaller.showDownload()  executed, but 
1.  "Step 1" show extention has been installed? but actually I didn't install extention
2. when I click Install Connect, nothing happened.
3. can I specify the version of Connect ? now it shows {3.9.1}
```
 const checkAsperaConnectStatus = () => {
        asperaUploadClient = new Connect({ connectMethod: 'http' });
        asperaInstaller = new ConnectInstaller({
            sdkLocation: '//d3gcli72yxqn2z.cloudfront.net/connect/v4'
        });

        asperaUploadClient.addEventListener(Connect.EVENT.STATUS, statusEventListener);
        asperaUploadClient.initSession();
    }



    const statusEventListener = function (eventType, data) {
        if (eventType === Connect.EVENT.STATUS && data === Connect.STATUS.INITIALIZING) {
            console.log('Aspera Connect Client is initializing');
            asperaInstaller.showLaunching();
        } else if (eventType === Connect.EVENT.STATUS && data === Connect.STATUS.FAILED) {
            console.log('Aspera Connect Client failed to load');
            asperaInstaller.showDownload();
        } else if (eventType === Connect.EVENT.STATUS && data === Connect.STATUS.OUTDATED) {
            console.log('Aspera Connect Client is Outdated');
            asperaInstaller.showUpdate();
        } else if (eventType === Connect.EVENT.STATUS && data === Connect.STATUS.RUNNING) {
            console.log('Aspera Connect Client is now Running');
            asperaInstaller.connected();
            asperaUploadClient.removeEventListener(Connect.EVENT.STATUS, statusEventListener);
        }
    };
```
![Capture](https://user-images.githubusercontent.com/66937705/161906421-7743c2e4-1a0f-4329-ada2-23fde735e116.PNG)

**Comment by dwosk** [comment]
Tracking the UI update for the HTTP strategy as described in (1) above in #18.

**Comment by dawei-medaitek** [comment]
Hi @dwosk , I found what caused mu issue, after read https://github.com/IBM/aspera-connect-sdk-js/blob/main/MIGRATION.md ,  My library version is NPM source v5.0.0-pre.1 , but the code method is  v4 (reference the example codes)  ,  now i change code to below, it works fine.
```
asperaUploadClient = new Connect({});
         asperaInstaller = new ConnectInstaller({});
```

**Comment by dwosk** [comment]
Ok great, glad the migration guide was able to clarify things. You can omit the empty objects when instantiating the classes to simplify things further:
```javascript
asperaUploadClient = new Connect();
asperaInstaller = new ConnectInstaller();
```
