### ISSUE TITLE
Is there any way to track whether Connect Installed and if not redirect to page for the user to install it.

### ISSUE THREAD

**Issue by chvasanthkumar** [IBM/aspera-connect-sdk-js#29]
For now the app is crashing and giving this error 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/107199719/186201526-220ce6bd-2547-4ac6-8606-efc11d28e41c.png)

**Comment by dwosk** [comment]
Hi @chvasanthkumar sorry I missed this issue. I've created #30 to add this to the documentation.

Something like this would be what you're looking for:
```
const connectClient = new AW4.Connect();

# Default UI client
# See: https://ibm.github.io/aspera-connect-sdk-js/AW4.ConnectInstaller.html
const connectInstaller = new AW4.ConnectInstaller();

const onStatusEvent = (eventType, data) => {
  # Exclude transfer type events
  if (eventType === AW4.Connect.EVENT.STATUS) return;

  # Check Connect status:
  #   FAILED --> Connect not installed
  #   RUNNING --> Connect installed and responding
  #   EXTENSION_INSTALL -> Connect extension not installed
  # See: https://ibm.github.io/aspera-connect-sdk-js/global.html#STATUS
  if (data == AW4.Connect.STATUS.FAILED) connectInstaller.showDownload();
  else if (data == AW4.Connect.STATUS.EXTENSION_INSTALL) connectInstaller.showExtensionInstall();
  else if (data == AW4.Connect.STATUS.RUNNING) connectInstaller.connected();
};

# Setup Connect status event listener
# See: https://ibm.github.io/aspera-connect-sdk-js/AW4.Connect.html#addEventListener
connectClient.addEventListener(AW4.Connect.EVENT.STATUS, onStatusEvent);

# Initialize Connect
connectClient.initSession();
```

Essentially, you can use the Connect status event listener to get updates on the Connect state. If you see `FAILED` then you can take that to mean that Connect is not installed. If you see `EXTENSION_INSTALL` then that means the user needs to install the browser extension. We provide a default UI via the `AW4.ConnectInstaller` class that you can use to show to the end user.

Regarding the crash, it's difficult to say just based off the console logs from the browser, would need more context.

**Comment by LKJREAL** [comment]
@dwosk It's really helpful.
Thanks and best regards.
LKJREAL.
