### ISSUE TITLE
Aspera SDK - Token issue when developing Javascript.

### ISSUE THREAD

**Issue by ks01301** [IBM/aspera-connect-sdk-js#31]
What we need
1. How to create and receive tokens using javascript.
2. Using curl to create permanent (semi-permanent) tokens instead of creating tokens for each file.

Reason.
Problems when generating disposable tokens.

Below is how to create a token that Ravi told you.
Can be created once using curl.

=====================
About test

node account
node id : test
node pw: test

download.json:

```json
{ 
"transfer_requests": [ 
{ "transfer_request": { 
"source_root": "/test", 
"remote_host": "192.168.200.240", 
"paths": [ { "source": "test2.txt" 
} 
] 
} 
} 
] 
}
```

```
curl -i -k -X POST -u test:test -d @C:\Users\knp\Desktop\download.json https://192.168.200.240:9092/files/download_setup

HTTP/1.1 200 OK
Cache: no-cache
Connection: close
Content-Type: application/json; charset=utf-8

{
"transfer_specs" : [
{
"transfer_spec" : {
"paths" : [
{
"source" : "test.json"
}
],
"source_root" : "/test/",
"destination_root" : "",
"token" : "ATM2_ACscsRUiIj8bJco62NaQ8c5Qohsasyg3mGs68-tURANUygAAF7QbULy3dbO9E3hI9DcaMD_2MTA",
"direction" : "receive",
"cipher" : "aes-128",
"tags" : null,
"rate_policy_allowed" : "fixed",
"rate_policy" : "fair",
"target_rate_kbps" : 10000,
"min_rate_kbps" : 0,
"remote_host" : "192.168.200.240",
"remote_user" : "test",
"sshfp" : null,
"ssh_port" : 33001,
"fasp_port" : 33001,
"http_fallback" : true,
"http_fallback_port" : 8443
}
}
]
}curl: (56) Failure when receiving data from the peer
```

JavaScript

```javascript
function download() {
    const transferSpec = {
      authentication: 'token',
      remote_host: '192.168.200.240',
      remote_user: 'test',
      source_root: '/test',
      paths: [{
        source: 'test2.txt'
    }],
      token: "ATM2_ACscsRUiIj8bJco62NaQ8c5Qohsasyg3mGs68-tURANUygAAF7QbULy3dbO9E3hI9DcaMD_2MTA",
      destination_root: '/',
      direction: 'receive'
    };
    console.log(transferSpec);
    this.client.startTransfer(transferSpec);
  }

    console.log(transferSpec);
    this.client.startTransfer(transferSpec);
  }
```

When I tested it as above, the file was sent normally.

========================
Using the above method, each time transmission is performed, 
a curl token must be generated.
To do that, we need to know how to create tokens with javascript.
Alternatively, we want to know how to create a permanent (semi-permanent) token using curl.

**Comment by dwosk** [comment]
This is more of a Node API question, but you should be able to call the Node API `download_setup` or `upload_setup` endpoints like you would any other API from JavaScript (using `fetch` or `axios` for example). The contents of the JSON file would simply be the body of the request (no actual file needed). A new token is required for each download because it depends on the transfer parameters (i.e. source file) and also has a valid time range so there's no concept of a permanent token. The closest thing would probably just be using password authentication which I wouldn't recommend for security reasons.

So retrieving a new token for each transfer is recommended, but I'd suggest you do it on the server side to protect your transfer server secrets. Something like this:

```
const fetch = require('node-fetch');
const https = require('https');

(async () => {
  const httpsAgent = new https.Agent({
    rejectUnauthorized: false // Quirk on the demo server
  });

  const body = {
    "transfer_requests" : [
    {
       "transfer_request" : {
          "source_root" : "/aspera-test-dir-tiny",
          "remote_host" : "demo.asperasoft.com",
          "paths" : [
            {
                "source" : "200KB.1"
            }
         ]
       }
    }
    ]
  };

  try {
    const response = await fetch('https://demo.asperasoft.com:9092/files/download_setup', {
      method: 'POST',
      body: JSON.stringify(body),
      headers: {
        'Authorization': 'Basic ' + Buffer.from('aspera:demoaspera', 'binary').toString('base64') // Should use environment variables for secrets
      },
      agent: httpsAgent
    });

    const data = await response.json();

    const { transfer_specs } = data;
    console.log(transfer_specs);
  } catch (error) {
    console.log(error);
  }
})();
```

**Comment by ks01301** [comment]
Is there a way to create tokens with Vanilla JavaScript or JQuery?

**Comment by laurent-martin** [comment]
There are the following types of tokens that can be used to authorize a transfer with Aspera:

-  Aspera Token: they start and end with `AT` and are generated by calling the node API endpoints: `/files/<upload|download>_setup` : typically NOT called directly by a client application, as it requires node api credentials which should usually not be disclosed on client application. But rather a broker application server does that after intermediate validations. That is the example shown earlier. Those tokens are encrypted/decrypted by the server, and have a limited lifespan (defined in aspera.conf)
- Basic token: you can use the node api credentials (either node user or access key) as above as token:
`'Basic ' + Buffer.from('user:pass', 'binary').toString('base64')`
- Bearer token (with also a time limit)

**Comment by laurent-martin** [comment]
Well, as answered earlier:

either use a basic token , but you expose the node credentials on client

or implement a server application that will call download_setup

example:

https://github.com/laurent-martin/aspera-api-examples/blob/main/httpgw/server.js

This example is for the HTTP gateway, but the server side can be used for Aspera Connect as well..

**Comment by ks01301** [comment]
We are not a node.js environment.
I want to know if there is a way to generate tokens from vanilla JavaScript or Jquery, not node.js environment.

**Comment by ks01301** [comment]
I also want to know if I can permanently transfer the file to docroot with the token issued by curl.

**Comment by laurent-martin** [comment]
Aspera (generaled by calling _setup API) and Bearer tokens are not permanent. (for security reasons).

If you want a permanent token, use the type "basic token" that you can generate as described in a post above.

**Comment by ks01301** [comment]
Can I ask you about basic token generation?

**Comment by laurent-martin** [comment]
Well,
It is written in my post previously...

```javascript
const node_user="abcd";
const node_pass="efgh";
const token='Basic ' + Buffer.from(node_user+':'+node_user, 'binary').toString('base64');
console.log(token);
```

**Comment by ks01301** [comment]
We are not a node.js environment.
It doesn't work if you insert the sample code you gave me.

**Comment by ks01301** [comment]
ERR_CERT_AUTHORITY_INVALID is occurring, so what should I do?

**Comment by laurent-martin** [comment]
Well...

This is not specific to Aspera:

For security reason, in a browser it is not possible to call an https endpoint with an invalid certificate (e.g. self signed, which is the default in HSTS).

So you have the following possibilities:

1. use the HTTP interface on HSTS: port 9091. it is not active by default, refer to hsts manual to see how to activate.
2. install a valid certificate on your server: it needs to be reach by a valid FQDN for which you have a TLS certificate. Refer to the HSTS manual on how to install.

**Comment by ks01301** [comment]
Thanks to you, I solved the problem.

Thank you so much
