### ISSUE TITLE
Aspera Connect is not recognized by the browser (Chrome)

### ISSUE THREAD

**Issue by jhrunning** [IBM/aspera-connect-sdk-js#44]
Hello,

We installed aspera connect on the user's PC, but the web browser keeps popping up asking us to install aspera connect.

We attached a screen (Aspera Connect error.jpg) that occurs when we access the aspera transfer page with Aspera connect installed and aspera connection test page access screen (Aspera test page error.jpg).
And the native message host debugging log was also collected because messages related to native host were found in the browser console log.
**Log File Download URL : [https://drive.google.com/file/d/16C6oWbMalMd0Uf0nxUxE3RnAIBWG4Z9h/view?usp=share_link](url)**

Other users can access and test https://test-connect.ibmaspera.com/ well, but this user above does not go to the next step on the loading screen even on the test page.
We have reinstalled browser extension and aspera connection (both 4.1.0 & 4.2.5) several times, but the issue has not been resolved

We tried accessing the web page before 3/30 and attached the log file, so please check.

OS : Windows 10 Enterprise 17763.3532
Chrome : 111.0.5563.146
Aspera Connect : 4.1.0
Aspera SDK : 4.1.0

Thank you

**Comment by jhrunning** [comment]
Hello, @dwosk 

1. We reinstalled Aspera Connect to the latest version of 4.2.5, but the issue has not been resolved.
2. The registry defines the location of the Chrome-nmh.json file and the file exists in the path.
3. I tested asperaconnect-nmh.exe command on my laptop before running it on the PC where the problem occurred, but when I enter the command, there is no response and no error message, is it a normal response?
(Connect is working fine on my laptop.)

The registry and manifest file screens can be downloaded from the following URL
[https://drive.google.com/file/d/1QzGXV8zDIWj22rcG8ySujdu7B2poVFEi/view?usp=share_link](url)

Thank you

**Comment by dwosk** [comment]
Is that the correct username listed in the registry key? Under that same Chrome registry folder, are there any keys related to Whitelist or Allowlist? Sometimes group policy can disable native messaging hosts from running.

At this point, I'd also suggest opening up the developer console on the test site, running `AW4.Logger.setLevel(2)` and refreshing the page (as mentioned [here](https://github.com/IBM/aspera-connect-sdk-js#troubleshooting)). Sometimes the browser will output some error messages related to starting the nmh.

**Comment by jhrunning** [comment]
Hello, @dwosk 

The compressed file I shared in the text also contains the log file of the developer console, and the file name is **230411_broswer console log.txt.**
The contents of this file are the results I collected after running the AW4.Logger.setLevel(2) command in the browser's developer console and refreshing the test page. 

I will check the user name and whitelist one more time.

Thank you

**Comment by dwosk** [comment]
Oops thanks you're right. Didn't see anything of interest in the console logs. I checked the chrome debug logs again and I noticed this log line:
```
[246876:252080:0509/113014.354:ERROR:native_process_launcher_win.cc(163)] COMSPEC is not set
```

I believe this could be the root cause. Chrome requires the `COMSPEC` environment variable to be set since it launches the nmh via this variable. For example, on my Windows machine I see:
```
ComSpec=C:\Windows\system32\cmd.exe
```

Set this environment variable globally on the machine, restart Chrome, and give it another try.

**Comment by jhrunning** [comment]
Hello, @dwosk 

The Aspera Connect issue has been resolved. The ComSpec environment variable you mentioned was the cause of the problem.

In CMD, the result of the command 'echo $ComSpec' is output normally, but the Windows environment variable list is missing ComSpec, so I added it and checked that Connect is responding in the browser.

Thank you

**Comment by jhrunning** [comment]
Thank you very much
