### ISSUE TITLE
Issues related to file transfer using Aspera connect.

### ISSUE THREAD

**Issue by Rosesook** [IBM/aspera-connect-sdk-js#47]
Hello.
[ Issues ]

This problem is that when you re-download an already existing file as shown in the screenshot below, the download itself proceeds normally, but Aspera Connect SDK's callback and EventListener do not work.

This is a problem that only occurs with  ZIP  files, and PDF files work fine even if they are downloaded again.

확인-IBM Aspera Connect

대상에 파일 이름이 같은 항목이 이미 있습니다. 계속하시겠습니까?

callback and EventListener are the METHODS below in the IBM_Aspera_Connect_SDK_4.1.0 API documentation.

startTransfer(transferSpec, connectSpec, callbacks)

addEventListener(type, listener)

Please solve this problem

**Comment by dwosk** [comment]
The callback and listener will not be triggered until the user closes the dialog.

If you want to avoid this dialog you can set `connectSpec.allow_dialogs` to `false`. See [here](https://ibm.github.io/aspera-connect-sdk-js/global.html#ConnectSpec) for documentation.
