### ISSUE TITLE
Why don't you use the transfer token in the upload example?

### ISSUE THREAD

**Issue by alexfrab** [IBM/aspera-connect-sdk-js#50]
We are trying to transfer files via the Aspera HttpGateway SDK.
First we created a transfer token via the API passing the following json in the body:
{
   "transfer_requests": [
     {
       "transfer_request": {
         "destination_root": "/data/aspera_xxx/folder",
         "token_life_seconds": 43200,
         "paths": [
             {
                 "source": "filename.txt",
                 "destination": "filename.txt"
             }
         ],
         "remote_host": "hosts",
         "cipher_allowed": "aes-128",
         "fasp_port": 33001,
         "ssh_port": 33001,
         "http_fallback": false,
         "http_fallback_port": 443,
         "https_fallback_port": 443,
         "rate_policy_allowed": "fixed",
         "rate_policy": "fair",
         "target_rate_kbps": 10000,
         "target_rate_cap_kbps": 20000
       }
     }
   ]
}

Once we have obtained the transfer token, we have created an html page where we call the following javascript code:

const transferSpec = {
         paths: [
             {
                 "source": "filename.txt",
                 "destination": "filename.txt"
             }
         ],
         destination_root: "/data/aspera_xxx/folder",
         token: <TRANSFER_TOKEN>,
         direction: "send",
         target_rate_cap_kbps: 20000,
         cipher: "aes-128",
         tags: null,
         rate_policy_allowed: "fixed",
         rate_policy: "fair",
         target_rate_kbps: 10000,
         min_rate_kbps: 0,
         lock_min_rate: true,
         remote_host: "hosts",
         remote_user: "xfer",
         sshfp: "a92abfb6d6b00b725cc47ce787639e1f2b192f3c",
         ssh_port: 33001,
         fasp_port: 33001,
         http_fallback: false,
         authentication: "tokens",
     };

For each attempt we get the error

Authorization refused: token doesn't match file list
[sdk_aspera.zip](https://github.com/IBM/aspera-connect-sdk-js/files/12323045/sdk_aspera.zip)

How can we fix this error?

**Comment by alexfrab** [comment]
Ok, thanks. 
Is there a repository or examples for aspera http gateway sdk?

**Comment by dwosk** [comment]
Hi @alexfrab apologies I missed your comment.

Please see the entry in the IBM API Hub here: https://developer.ibm.com/apis/catalog/aspera--aspera-http-gateway-javascript-sdk/Introduction/
