### ISSUE TITLE
Can aspera docroot path have bucket along with folder specified for s3 download?

### ISSUE THREAD

**Issue by AakankshaBhatia** [IBM/aspera-connect-sdk-js#56]
Hi Team,

I need to download file from S3 bucket to local system using aspera sdk(directly from S3 to local). 

The source file path is as below:
https://xyz.s3.region.amazonaws.com/Folder1/2023/others/File.mp4
where 
**xyz = bucket name** 
**/Folder1/2023/others/File.mp4 = file path**

The docroot specified in the aspera.conf file for user is as below:
s3://xcsfsfqrqwrqwr%2B@s3.amazonaws.com/xyz
where 
**xyz = bucket name** 

Is it possible to specify the docroot path having folder name also, as below ? so that the aspera user has access to only the given folder under the bucket, and not the whole bucket.
s3://xcsfsfqrqwrqwr%2B@s3.amazonaws.com/xyz/Folder1
where 
**xyz = bucket name** 
**Folder1 = folder **

Thanks in advance.

**Comment by dwosk** [comment]
@AakankshaBhatia as this seems to be related to Aspera HSTS configuration and not the Aspera Connect SDK, can I ask that you redirect your question to [IBM Support](https://www.ibm.com/mysupport/s/?language=en_US) so that it can be directed to the appropriate SME?

**Comment by AakankshaBhatia** [comment]
Sure @dwosk , thanks for reply.
