### ISSUE TITLE
Failed Connect SDK transfer request on HSTE

### ISSUE THREAD

**Issue by jhrunning** [IBM/aspera-connect-sdk-js#65]
Hello,

We have installed HST Endpoint for use in conjunction with the web using the Connect SDK.
However, an error occurred during the transfer test on the web, so we're inquiring.

Currently, the same web server is using the SDK to connect to the HST Server normally, but file transfer is not working properly while connecting the HST Endpoint.

We attached the log that we tried to test today, so please check it
(HSTE has no logs and includes client logs and console logs from Web browser developer tools,
The content of "web_browser_console log.txt" is the  developer mode console message of the web browser developer tool)

Thank you

[240522_log.zip](https://github.com/IBM/aspera-connect-sdk-js/files/15400538/240522_log.zip)

**Comment by dwosk** [comment]
> but file transfer is not working properly while connecting the HST Endpoint.

Can you provide more details about the error you see? Do you see the transfer starting in Connect but it fails? Or is the error elsewhere?

I see you are running a fairly old version of the client. 4.1.1 was released almost 4 years ago. Depending on the error, upgrading to the latest version of Connect may give you better results.

**Comment by jhrunning** [comment]
Hello,

When we run a file transfer from the web browser, the transfer pop-up pops up and no longer proceeds, and nothing happens to the Aspera Connect activity on the task bar, Aspera Connect log, and HST Endpoint log.

Attached a transfer pop-up window and a console screen in developer mode
![Dev_mod_Console_msg](https://github.com/IBM/aspera-connect-sdk-js/assets/132983897/e4883df2-ee7c-450d-9e20-ff96f851b6ce)
![Transfer Popup](https://github.com/IBM/aspera-connect-sdk-js/assets/132983897/1fdb0843-a786-4780-9db9-0f8b9c803b60)


With the current version of Aspera Connect, file transfer will proceed normally to HSTS through the SDK of the web portal, could Connect's version be a problem? The HST Endpoint version is  4.4.2.550 and is installed on RHEL 7.9.

There is no HST Endpoint version in the text, it is installed on RHEL 8.4 and is 4.4.3.891.

Thank you

**Comment by dwosk** [comment]
If you don't see anything happen in Connect's activity window (i.e. you don't see the transfer appearing) then I suspect that the web app never makes the call to start the transfer.

Do you check that Connect is running before making the start transfer call? If you were attempting to start the transfer before Connect was running, I would expect to see some sort of error in the developer console, which I don't see. All I see are a few warnings that probably correspond to the requests from the transfer event listener.

So I suspect the issue is somewhere on the integration side of things. Are you using token-based authentication for these transfers? If so, then you must be making a download_setup/upload_setup call to the transfer server to retrieve the token. Is that request succeeding when going against the HSTE?

**Comment by jhrunning** [comment]
Hello,

During the transfer test process, we checked the Aspera Connect icon on the task bar and monitored the activity window as well. And we even checked that Connect starts automatically when we shut down Connect and open the transfer page of the web portal.

How can we verify using token-based authentication in the transfer process?
Below is some of the web server source code, is it correct that it is related to token-based authentication?

function getTransferSpec(remoteHost, sourcePath, destPath ,direction, unixAcc, token){
	var transferSpec = {
			"paths": [],
			"remote_host": remoteHost,
			"remote_user": "root",
			"authentication" : "token", 
			"token" : token,
			"direction": direction,
			"destination_root": destPath,
			"ssh_port" : 33001,
			"create_dir" : true,
			"target_rate_kbps" : 1000000,
			"cookie" : unixAcc + "-" + new Date().getTime()
	};


Below is the message of download_setup/upload_setup call against HTSE.
HTTP/1.1 500 Internal Server Error
"error" : { "code" : 500, "reason" : "Internal Server Error", "user_message" : "Storage root is not configured." }

The docroot of the HSTE is set and aspera service is running normally.
[yjkim@ws2002997-97: /user/yjkim ]/opt/aspera/bin/asuserdata -u root | grep absolute
	canonical_absolute: "/"
	absolute: "/"

We attached the result of a call and netstat, ps command against HSTE as a file, so please check it.
[aspera-test-log_curl_command.txt](https://github.com/IBM/aspera-connect-sdk-js/files/15430800/aspera-test-log_curl_command.txt)
[netstat_ps_command.txt](https://github.com/IBM/aspera-connect-sdk-js/files/15430803/netstat_ps_command.txt)

And the customer's web server is requesting file transfer to HSTE using Java API, could this be a problem?

Thank you

**Comment by laurent-martin** [comment]
@jhrunning, 
The message  "Storage root is not configured." means:
 "Storage root associated with transfer user is not configured."
If you changed the docroot (asconfigurator, or aspera.conf), you need to perform the following after change:
either restart asperanoded, or execute asnodeadmin --reload

when using token, the node api user shall be associated with the same transfer used as used in transfer spec.
in fact, the normal way for Aspera Token type (AT) is to call /files/(upload|download|async)_setup with node api user, and it returns a full transfer, which can be modifed (e.g. ass cookie, or tags, or change anything), and the "remote_user" (transfer user) is the right one.

All this can be tested relatively easily using `ascli` : 
`ascli node upload 'faux:///test.bin?1m' --transfer=connect --url=https://nodehost:9092 --username=nodeuser --password=password --log-level=trace2`

This calls the node api, and starts connect with logs.
