### ISSUE TITLE
SDK 5.0.1 cannot access connect-sdk.js

### ISSUE THREAD

**Issue by jdjinesta** [IBM/aspera-connect-sdk-js#81]
Hello Team,

SDK 5.0.0 is working fine when trying to access this file

https://d3gcli72yxqn2z.cloudfront.net/@ibm-aspera/connect-sdk-js/v5.0.0/connect-sdk.js

However using 5.0.1 is failing with this message

https://d3gcli72yxqn2z.cloudfront.net/@ibm-aspera/connect-sdk-js/v5.0.1/connect-sdk.js

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>@ibm-aspera/connect-sdk-js/v5.0.1/connect-sdk.js</Key>
<RequestId>P914BMSDS1KSTNKZ</RequestId>
<HostId>p3HQpW1vQGkFv4G1pd8ZxxVhxfzwx4dckoIC+fn6gQLVBgI4L6fVlsjgLQgJkgQpd9jEMjKMyHM=</HostId>
</Error>

Appreciate your help to check this issue.

Regards,
Juan Diego Jinesta

**Comment by dwosk** [comment]
Hi @jdjinesta, we've fixed the CDN deployment. The following links are now working, please try again:

* https://d3gcli72yxqn2z.cloudfront.net/@ibm-aspera/connect-sdk-js/latest/connect-sdk.js
* https://d3gcli72yxqn2z.cloudfront.net/@ibm-aspera/connect-sdk-js/v5.0.1/connect-sdk.js

**Comment by mattastarita** [comment]
Thanks, I can confirm that it is working for us too now. thanks again team.
