### ISSUE TITLE
SDK v5.0.1 is unable to install the Connect Client and Extension

### ISSUE THREAD

**Issue by jdjinesta** [IBM/aspera-connect-sdk-js#84]
After changing the aspera sdk version to v5.0.1, users are unable to install the Connect Client and Extension i.e., the popup itself is not coming. But just changing the version to v5.0.0 (just changing the link without any other changes), users are getting the popup to install Extension and Connect.
![browser_error_connect_sdk_501](https://github.com/user-attachments/assets/ebbc7f13-af01-4ac5-a943-f76f52561a80)

**Comment by JAHMCR** [comment]
Hello @jdjinesta,

We are currently working on a fix for this issue, will be addressed in version`5.0.2`

**Comment by JAHMCR** [comment]
Hello @jdjinesta,

We have already addressed the issue, it is very likely to be deployed today

**Comment by jdjinesta** [comment]
Hi Team,

Is there any ETA for delivering 5.0.2 ? 

Regards,

**Comment by dwosk** [comment]
@jdjinesta we've just released the fix and is available in `v5.0.3`.

If using the CDN, you may now point to `https://d3gcli72yxqn2z.cloudfront.net/@ibm-aspera/connect-sdk-js/v5.0.3/connect-sdk.min.js`
